Prp.Sln/Controllers/ContentPageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

using Prp.Data;

namespace Prp.Sln.Controllers
{
    public class ContentPageController : BaseLoginController
    {
        // GET: ContentPage
        public ActionResult PrivatePolicy()
        {
            ContentPageModel model = new ContentPageModel();
            return View(model);
        }

        public ActionResult TermAndCondition()
        {
            ContentPageModel model = new ContentPageModel();
            return View(model);
        }

        public ActionResult Notifications()
        {
            ContentPageModel model = new ContentPageModel();
            return View(model);
        }


        public ActionResult JobListing()
        {
            SpecialityJobModel model = new SpecialityJobModel();

            int typeId = Request.QueryString["typeId"].TooInt();

            model.listDegreeType = new ConstantDAL().GetAll(ProjConstant.Constant.degreeType).OrderBy(x => x.id).ToList();

            model.listQouta = new ConstantDAL().GetAll(ProjConstant.Constant.qoutaType).OrderBy(x => x.id).ToList();

            if (typeId == 0)
                typeId = model.listDegreeType.FirstOrDefault().id.TooInt();


            model.typeId = typeId;

            model.listSpecialityJob = new SpecialityDAL().GetSpecialityJobByTypeId(1, typeId);
            return View(model);
        }



        public ActionResult TestSMS()
        {
            ContentPageModel model = new ContentPageModel();

            Message msg = new Message();

            try
            {
                string number = Request.QueryString["number"].ToString();
                string message = "Dear Applicant, the testing message";
                msg = FunctionUI.SendSms(number, message);

                model.msg = msg.msg;
                model.content = msg.message;
            }
            catch (Exception ex)
            {
                model.msg = "Error";
                model.content = ex.Message;
            }
            return View(model);
        }

        public ActionResult TestEmail()
        {
            ContentPageModel model = new ContentPageModel();
            Message msg = new Message();
            try
            {
                string email = Request.QueryString["email"].TooString();
                if (!String.IsNullOrWhiteSpace(email))
                {
                    string body = "Test Body";
                    msg = email.SendEmail("Test Subject", "Test Title", body);
                    if (msg.status == true)
                    {
                        model.msg = "Email sent";
                    }
                    else
                    {
                        model.msg = msg.message;
                    }

                    model.key = email;
                }
                else
                {
                    model.key = email;
                    model.msg = "Email not provided.";
                }
               
            }
            catch (Exception)
            {

            }
            return View(model);
        }

        public ActionResult TestEmailCredentials()
        {
            ContentPageModel model = new ContentPageModel();
          

            ViewBag.message = TempData["MessageEmail"];
            return View(model);
        }

        [ValidateInput(false)]
        public ActionResult TestAndSendEmail(ContentPageModel ModelSave, HttpPostedFileBase files)
        {
            EmailEntity email = ModelSave.email;


            Message msg = new Message();
            try
            {

                

                string password = email.password.ToString();
                string mailServer = WebConfigurationManager.AppSettings["MailServer"].ToString();
                int mailPort = WebConfigurationManager.AppSettings["MailPort"].TooInt();
                bool mailSSL = WebConfigurationManager.AppSettings["MailSSl"].TooBoolean();
                bool useDefaultCredentials = WebConfigurationManager.AppSettings["UseDefaultCredentials"].TooBoolean();

                var fromAddress = new MailAddress(email.emailFrom, email.title);
                var toAddress = new MailAddress(email.emailId);

                //MailAddress addressBCC = new MailAddress("phf.it.waheedahmad@gmail.com");

                var smtp = new SmtpClient
                {
                    Host = mailServer,
                    Port = mailPort,
                    EnableSsl = mailSSL,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = useDefaultCredentials,
                    Credentials = new NetworkCredential(fromAddress.Address, password)
                };
                using (var message = new MailMessage(fromAddress, toAddress)
                {
                    IsBodyHtml = true,
                    Subject = email.subject,
                    Body = email.body
                })
                {
                    smtp.Send(message);
                }
                msg.status = true;
                msg.message = "Sent";

            }
            catch (Exception ex)
            {
                msg.status = false;
                msg.message = ex.Message;
            }

            TempData["MessageEmail"] = msg;

            return Redirect("/email-test-credentials");
        }


        public Message TestingSMSSend()
        {
            Message msg = new Message();
            string message = "Dear Applicant, the testing message";
            try
            {
                msg = FunctionUI.SendSms("03038132009", message);
            }
            catch (Exception)
            {
                msg = new Message();
            }
            return msg;
        }
    }
}

Prp.Sln/Views/ContentPage/JobListing.cshtml
@{
    ViewBag.Title = "JobListing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Prp.Sln.SpecialityJobModel

@section RenderCss{

    <style>

        td span {
            line-height: 18px;
        }

        #divprint {
            width: 100%;
            margin: 0 auto;
            margin-top: 15px;
            font-family: 'Lato', sans-serif !important;
        }

        .center-div {
            margin: auto;
            width: 50%;
            padding: 10px;
            height: 60px;
        }

        .btn_print {
            padding: 10px 40px;
            background-color: #48a0d7;
            border-radius: 5px
        }

        .ank {
            cursor: pointer;
        }

        .spn-img-view {
            font-style: italic;
        }

        .spn-edit {
            float: right;
            margin-right: 5px;
            padding: 1px 6px;
            background: #fefefe;
            color: #8b8686;
        }

            .spn-edit:hover {
                background: #e9e0e0;
            }

        .imgView {
            width: 60px;
            height: 40px;
            border: 1px solid #ede9e9;
            width: 30px;
            height: 20px;
        }


        .text-center {
            text-align: center;
            text-align: -webkit-center;
            text-align: -moz-center;
        }

        .top_detail tr td:nth-child(2n) {
            border-bottom: 1px solid #000;
        }
    </style>
}
@section RenderScript{

    <script>

        var typeId = 0;

        $(document).ready(function () {

            typeId = $("#hfdTypeId").val();
            $("#ddlType").val(typeId);
            $(document).on('change', '#ddlType', function () {
                typeId = $(this).val();
                window.location.href = "/induction/jobs-post?typeId=" + typeId;
            });

            $(document).on('click', '.btn_print', function () {

                printDiv();

            });

        });

        function printDiv() {

            var result = false;
            try {

                var divToPrint = document.getElementById('divprint');
                var newWin = window.open('', 'Print-Window');
                newWin.document.open();
                newWin.document.write('<html><body onload="window.print()">' + divToPrint.innerHTML + '</body></html>');
                newWin.document.close();
                setTimeout(function () { newWin.close(); }, 10);
                result = true;

            } catch (e) {
                result = false;
            }
            return result;
        }
    </script>
}
<div class="container" style=" margin-bottom:60px;">
    <div class="row main">
        <div class="col-sm-12 form-box">
            <div class="main-login main-center">
                <form class="form-horizontal">
                    <h3 class="heading">
                        Job post list
                    </h3>
                    <div class="col-sm-12" style="display:none;">
                        <div class="center-div">
                            <a class="btn btn-app animated-button btn_print"><i class="fa fa-save"></i> &nbsp; Print </a>
                        </div>
                    </div>
                    <div class="row cols-sm-12">
                        <input type="hidden" id="hfdTypeId" value="@(Model.typeId)" />
                        <div class="center-div">
                            Select Type :

                            <select id="ddlType" name="ddlType" class="form-control">
                                @foreach (var item in Model.listDegreeType)
                                {
                                    <option value="@(item.id)"> @item.name </option>
                                }
                            </select>
                        </div>


                    </div>
                    <div>
                        <div id="divprint" class="container cv-f" style="font-size:14px !important; ">
                            @{
                                if (Model.listQouta != null && Model.listQouta.Count > 0)
                                {
                                    foreach (var qt in Model.listQouta)
                                    {
                                        var listSpecility = Model.listSpecialityJob.Where(x => x.quotaId == qt.id).ToList();
                                        if (listSpecility != null && listSpecility.Count > 0)
                                        {
                                            var sr = 0;
                                            <table style="margin-top: 15px; width: 100%;" cellspacing="0">
                                                <tbody>
                                                    <tr>
                                                        <td style="background-color: #8b8686; -webkit-print-color-adjust: exact;">
                                                            <p style="margin: 6px;color: #fff; font-size: 16px;">
                                                                @qt.name
                                                            </p>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table border="1" style="font-size:14px; width: 100%;" cellspacing="0">
                                                <thead>
                                                    <tr>
                                                        <th>Sr.</th>
                                                        <th>Sepecility</th>
                                                        <th> Hospital</th>
                                                        <th> Seats</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var spc in listSpecility.OrderBy(x => x.specialityName))
                                                    {
                                                        sr = sr + 1;
                                                        <tr>
                                                            <td>@sr</td>
                                                            <td>@spc.specialityName</td>
                                                            <td>@spc.hospitalName</td>
                                                            <td>@spc.jobs</td>
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        }
                                    }
                                }
                            }
                        </div>
                    </div>
                    <div class="row cols-sm-12">
                        &nbsp; &nbsp; &nbsp; &nbsp;
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Prp.Sln/Views/ContentPage/Notifications.cshtml
@{
    ViewBag.Title = "Notifications";
    Layout = "~/Areas/nadmin/Views/Shared/_LayoutPrint.cshtml";
}

<h2>Notifications</h2>

Prp.Sln/Views/ContentPage/PrivatePolicy.cshtml
@{
    ViewBag.Title = "Private Policy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Prp.Sln.ContentPageModel
@section RenderCss{

   

}
@section RenderScript{

    <script>

      

    </script>

}
<div class="container">
    <div class="row main">
        <div class="col-xs-12 col-md-12 form-box">
            <div class="entry-content">
                <h3 class="text-red">Statement of Privacy</h3>
                <p>
                    Policy and Procedure Manual (PPM) of Post-Graduate Residency (PGR) of Level-III Program... <a href="https://health.punjab.gov.pk/" target="_blank">Read more</a>
                </p>
            </div>
        </div>
    </div>
</div>

Prp.Sln/Views/ContentPage/TermAndCondition.cshtml
@{
    ViewBag.Title = "Term and Condition";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Prp.Sln.ContentPageModel
@section RenderCss{
}

@section RenderScript{
    <script>

    </script>
}
<div class="container">
    <div class="row main">
        <div class="col-xs-12 col-md-12 form-box">
            <div class="entry-content">
                <h3 class="text-red">Terms and Conditions</h3>
                <p>
                    1. PPM 2021  <a href="/docs/398POLICIY-PG-LEVEL-III.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    2. Latest House Job Notification <a href="/docs/houseJob2.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    3. House Job Notification   <a href="/docs/houseJob1.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    4. NEB and Attempts Marks Notification  <a href="/docs/attemptsMarks.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    5. User Manual  <a href="/docs/User-Manual-PRP.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    6. Advertisement  <a href="/docs/advertisment.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    7. Check list for candidate  <a href="/docs/apply-checklist.jpeg" target="_blank">Read more</a>
                </p>
                <p>
                    8. Check list for foreigner  <a href="/docs/Foreign_Quota_Induction_Criteria.pdf" target="_blank">Read more</a>
                </p>
            </div>
            <div class="entry-content">
                <h3 class="text-red">Seats</h3>
                <p>
                    1. FCPS  <a href="/docs/fcps.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    2. MS  <a href="/docs/ms.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    3. MD  <a href="/docs/md.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    4. MDS  <a href="/docs/mds.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    4. FCPS Dentistry  <a href="/docs/fcpsd.pdf" target="_blank">Read more</a>
                </p>
            </div>
        </div>
    </div>
</div>

Prp.Sln/Views/ContentPage/TermAndCondition__.cshtml
@{
    ViewBag.Title = "Term and Condition";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Prp.Sln.ContentPageModel
@section RenderCss{
}

@section RenderScript{
    <script>

    </script>
}
<div class="container">
    <div class="row main">
        <div class="col-xs-12 col-md-12 form-box">
            <div class="entry-content">
                <h3 class="text-red">Terms and Conditions</h3>
                <p>
                    1. PPM 2021  <a href="/docs/398POLICIY-PG-LEVEL-III.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    2. Latest House Job Notification <a href="/docs/houseJob2.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    3. House Job Notification   <a href="/docs/houseJob1.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    4. User Manual  <a href="/docs/User-Manual-PRP.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    5. Advertisement  <a href="/docs/advertisment.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    6. Check list for candidate  <a href="/docs/apply-checklist.jpeg" target="_blank">Read more</a>
                </p>
                <p>
                    7. Check list for foreigner  <a href="/docs/Foreign_Quota_Induction_Criteria.pdf" target="_blank">Read more</a>
                </p>
            </div>
            <div class="entry-content">
                <h3 class="text-red">Seats</h3>
                <p>
                    1. FCPS  <a href="/docs/fcps.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    2. MS  <a href="/docs/ms.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    3. MD  <a href="/docs/md.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    4. MDS  <a href="/docs/mds.pdf" target="_blank">Read more</a>
                </p>
                <p>
                    4. FCPS Dentistry  <a href="/docs/fcpsd.pdf" target="_blank">Read more</a>
                </p>
            </div>
        </div>
    </div>
</div>

Prp.Sln/Views/ContentPage/TestEmail.cshtml
@{
    ViewBag.Title = "Private Policy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Prp.Sln.ContentPageModel
@section RenderCss{

    <style>
        .form-box {
            margin-bottom: 60px;
        }
    </style>

}
@section RenderScript{

    <script>

        $(document).ready(function () {
            $("#divBgImage").removeClass("bg-img");
        });

    </script>
}
<div class="container">
    <div class="row main">
        <div class="col-xs-12 col-md-12 form-box">
            <div class="entry-content">
                <h3 class="text-red">Result</h3>
                <br />
                <p> Key :  @Model.key</p>
                <p>
                    Message:  @Model.msg
                </p>
                <p>
                   
                </p>
            </div>
        </div>
    </div>
</div>

Prp.Sln/Views/ContentPage/TestEmailCredentials.cshtml
@model Prp.Sln.ContentPageModel
@{
    ViewBag.Title = "Test Email Credentials";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section RenderCss{

    <style>
        .query-new {
            background-color: #f95454;
            padding: 5px 10px;
            border-radius: 5px;
            color: #fff;
        }

        .query-old {
            background-color: #61aa2f;
            padding: 5px 10px;
            border-radius: 5px;
            color: #fff;
        }

        .spdetail {
            font-size: 12px;
            font-style: italic;
            color: #0a26ed;
            cursor: pointer;
        }
    </style>

}
@section RenderScript{


    <script src='https://www.google.com/recaptcha/api.js'></script>

    <script>

        $(document).ready(function () {


            

        });


        function SetValueAndValidateForm(event) {

            var isOk = true;

            //var emailId = $("#txtEmail").val().toLowerCase();


            //if (ValidateEmail(emailId) == false) {
            //    isOk = false;
            //    alert("Please enter valid emailId")
            //}

            if (isOk == false)
                event.preventDefault();
        }

    </script>

}
<div class="container content">
    <div class="row main">

        <div class="col-sm-12 form-box">
            <div class="main-login main-center">

                @if (ViewBag != null && ViewBag.message != null)
                {
                    var message = ViewBag.message.message;
                    var classType = "panel-success";

                    if (ViewBag.message.status == false)
                    {
                        classType = "panel-danger";
                        if (String.IsNullOrWhiteSpace(message))
                        {
                            message = " Something went wrong.";
                        }
                    }
                    <div id="divMessagedd" class="col-sm-12">
                        <div id="divMsgdd" class="@("panel "+ classType )">
                            <div class="panel-heading">
                                <label class="text-center">
                                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                    <ul id="idErrorMsg" class="ul-err">
                                        @message
                                    </ul>
                                </label>
                            </div>
                        </div>
                    </div>
                }

                @using (Html.BeginForm("TestAndSendEmail", "ContentPage", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = " SetValueAndValidateForm(event)" }))
                {
                    <form class="form-horizontal">

                        <h3 class="heading">Test Email Credentials</h3>
                        <hr class="colorgraph">
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label> Email From <span class="sprq">*</span></label>
                                    @Html.TextBoxFor(a => a.email.emailFrom, new { @class = "form-control ctrlUnq", @required = "required", @id = "txtEmailId", @tabindex = "1" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label> Password <span class="sprq">*</span></label>
                                    @Html.TextBoxFor(a => a.email.password, new { @class = "form-control ctrlUnq", @required = "required", @id = "txtPassword", @tabindex = "1" })
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label> Email To <span class="sprq">*</span></label>
                                    @Html.TextBoxFor(a => a.email.emailId, new { @class = "form-control ctrlUnq", @required = "required", @id = "txtEmailId", @tabindex = "2" })
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label> Title <span class="sprq">*</span></label>
                                    @Html.TextBoxFor(a => a.email.title, new { @class = "form-control", @required = "required", @id = "txtTitle", @tabindex = "3" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <label> Subject <span class="sprq">*</span></label>
                                    @Html.TextBoxFor(a => a.email.subject, new { @class = "form-control", @required = "required", @id = "txtSubject", @tabindex = "3" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <label> Body/Message <span class="sprq">*</span></label>
                                    @Html.TextAreaFor(model => model.email.body, new { @class = "form-control", @required = "required", @rows = "8", @id = "txtBody", @tabindex = "3" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12" style="margin:10px 0px 20px 0px;">
                                <div class="col-sm-4">
                                </div>
                                <div class="col-sm-4">
                                    <button type="submit" class="btn btn-app animated-button" style="width:100%">Send Email</button>
                                </div>
                                <div class="col-sm-4">
                                </div>
                            </div>
                        </div>

                    </form>
                }
            
            </div>
        </div>
    </div>
</div>

Prp.Sln/Views/ContentPage/TestSMS.cshtml
@{
    ViewBag.Title = "SMS | Test Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Prp.Sln.ContentPageModel
@section RenderCss{

    <style>
        .form-box {
            margin-bottom: 60px;
        }
    </style>

}
@section RenderScript{

    <script>

        $(document).ready(function () {
            $("#divBgImage").removeClass("bg-img");
        });

    </script>
}
<div class="container">
    <div class="row main">
        <div class="col-xs-12 col-md-12 form-box">
            <div class="entry-content">
                <h3 class="text-red">Result</h3>
                <br />
                <p> Key :  @Model.key</p>
                <p>
                    Status:  @Model.msg
                </p>
                <p>
                    Message:  @Model.content
                </p>
            </div>
        </div>
    </div>
</div>